name: build_stable

on:
  push:
    branches: [ 3.2.x ]

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 2
  CTEST_PARALLEL_LEVEL: 1
  CTEST_OUTPUT_ON_FAILURE: 1
  OMPI_ALLOW_RUN_AS_ROOT: 1
  OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
  OMPI_MCA_rmaps_base_oversubscribe: "yes"

permissions:
  contents: write

jobs:
  build:

    strategy:
      fail-fast: false

    runs-on: ubuntu-latest
    container:
      image: ghcr.io/triqs/solid_dmft_github_ci:3.2.x

    steps:
      - uses: actions/checkout@v4

      - name: Build solid_dmft
        run: |
          cmake -S . -B build/
          cmake --build build/ --verbose

      - name: Test solid_dmft
        run: |
          cmake --build build/ --target test

